// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJ4nkPInCLRRhuLXGAhjnG6u3RDYttY8c',
    appId: '1:957555021833:web:0ca335d299eb6e32adc0d8',
    messagingSenderId: '957555021833',
    projectId: 'flutterfirebasedemo-75426',
    authDomain: 'flutterfirebasedemo-75426.firebaseapp.com',
    storageBucket: 'flutterfirebasedemo-75426.firebasestorage.app',
    measurementId: 'G-433Z6X0DGR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxdmcrTFx-cLD0SHEzXIrovSHV-mK2KLQ',
    appId: '1:957555021833:android:11a843ce1f878205adc0d8',
    messagingSenderId: '957555021833',
    projectId: 'flutterfirebasedemo-75426',
    storageBucket: 'flutterfirebasedemo-75426.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhoFogZ-7YNxiNGbTd99vUxcYzZovHBLw',
    appId: '1:957555021833:ios:4c309c8765471753adc0d8',
    messagingSenderId: '957555021833',
    projectId: 'flutterfirebasedemo-75426',
    storageBucket: 'flutterfirebasedemo-75426.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhoFogZ-7YNxiNGbTd99vUxcYzZovHBLw',
    appId: '1:957555021833:ios:4c309c8765471753adc0d8',
    messagingSenderId: '957555021833',
    projectId: 'flutterfirebasedemo-75426',
    storageBucket: 'flutterfirebasedemo-75426.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJ4nkPInCLRRhuLXGAhjnG6u3RDYttY8c',
    appId: '1:957555021833:web:e6dedf63d639a240adc0d8',
    messagingSenderId: '957555021833',
    projectId: 'flutterfirebasedemo-75426',
    authDomain: 'flutterfirebasedemo-75426.firebaseapp.com',
    storageBucket: 'flutterfirebasedemo-75426.firebasestorage.app',
    measurementId: 'G-BW7XVHFTVE',
  );
}
